-- ================================================================
-- ORDER TRACKING SYSTEM — MIGRATION
-- Run this in Supabase SQL Editor (Project → SQL Editor → New Query)
-- ================================================================

-- 1. Add is_main to product_variants (was missing from original schema)
ALTER TABLE public.product_variants
    ADD COLUMN IF NOT EXISTS is_main BOOLEAN DEFAULT false;

-- 2. Add tracking fields to orders
ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(150),
    ADD COLUMN IF NOT EXISTS shipping_provider VARCHAR(100),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- Also fix shipments table (address column was missing in original create)
ALTER TABLE public.shipments
    ADD COLUMN IF NOT EXISTS address TEXT;

-- 3. Create order_status_logs (full history)
CREATE TABLE IF NOT EXISTS public.order_status_logs (
    log_id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id     INT NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
    status       VARCHAR(50) NOT NULL,
    changed_by   VARCHAR(100) DEFAULT 'system',
    note         TEXT,
    created_at   TIMESTAMPTZ DEFAULT now()
);

-- 4. Recreate order_list_view with new columns
CREATE OR REPLACE VIEW public.order_list_view AS
SELECT
    o.order_id,
    o.user_id,
    o.total_amount,
    o.status,
    o.payment_status,
    o.tracking_number,
    o.shipping_provider,
    o.created_at,
    o.updated_at,
    s.status         AS shipment_status,
    s.tracking_number AS shipment_tracking,
    s.address,
    u.full_name      AS customer_name,
    u.phone_number
FROM public.orders o
LEFT JOIN public.shipments s ON o.order_id = s.order_id
LEFT JOIN public.users u ON o.user_id = u.id;

-- 5. Indexes for performance
CREATE INDEX IF NOT EXISTS idx_orders_status
    ON public.orders(status);

CREATE INDEX IF NOT EXISTS idx_orders_user_id
    ON public.orders(user_id);

CREATE INDEX IF NOT EXISTS idx_orders_created_at
    ON public.orders(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_order_status_logs_order_id
    ON public.order_status_logs(order_id);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id
    ON public.order_items(order_id);
