-- ==========================================
-- 1. USERS & ADDRESSES
-- ==========================================
CREATE TABLE public.users (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  phone_number VARCHAR(255) UNIQUE,
  full_name VARCHAR(255),
  role VARCHAR(50) DEFAULT 'customer',
  is_active BOOLEAN DEFAULT true
);


CREATE TABLE public.user_addresses (
  address_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INT REFERENCES public.users(id) ON DELETE CASCADE,
  recipient_name VARCHAR(255),
  address_line TEXT
);

-- ==========================================
-- 2. PRODUCTS & CATEGORIES
-- ==========================================
CREATE TABLE public.categories (
  category_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  parent_id INT REFERENCES public.categories(category_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.products (
  product_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  category_id INT REFERENCES public.categories(category_id) ON DELETE SET NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.product_variants (
  variant_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id INT REFERENCES public.products(product_id) ON DELETE CASCADE,
  sku VARCHAR(100) UNIQUE,
  price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  stock_quantity INT DEFAULT 0,
  image_url TEXT,
  unit VARCHAR(50),
  low_stock_threshold INT DEFAULT 5,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ==========================================
-- 3. CARTS
-- ==========================================
CREATE TABLE public.carts (
  cart_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INT UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.cart_items (
  cart_item_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cart_id INT REFERENCES public.carts(cart_id) ON DELETE CASCADE,
  variant_id INT REFERENCES public.product_variants(variant_id) ON DELETE CASCADE,
  quantity INT NOT NULL CHECK (quantity > 0)
);

-- ==========================================
-- 4. ORDERS
-- ==========================================
CREATE TABLE public.orders (
  order_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INT REFERENCES public.users(id) ON DELETE SET NULL,
  total_amount NUMERIC(10,2) NOT NULL CHECK (total_amount >= 0),
  status VARCHAR(50) DEFAULT 'pending',
  payment_status VARCHAR(50) DEFAULT 'unpaid',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.order_items (
  order_item_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id INT REFERENCES public.orders(order_id) ON DELETE CASCADE,
  variant_id INT REFERENCES public.product_variants(variant_id) ON DELETE SET NULL,
  price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  quantity INT NOT NULL CHECK (quantity > 0)
);

-- ==========================================
-- 5. PAYMENTS & SHIPMENTS
-- ==========================================
CREATE TABLE public.payments (
  payment_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id INT REFERENCES public.orders(order_id) ON DELETE CASCADE,
  method VARCHAR(100),
  transaction_ref TEXT,
  paid_at TIMESTAMPTZ,
  status VARCHAR(50) DEFAULT 'pending'
);

CREATE TABLE public.shipments (
  shipment_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id INT REFERENCES public.orders(order_id) ON DELETE CASCADE,
  address_id INT REFERENCES public.user_addresses(address_id) ON DELETE SET NULL,
  tracking_number VARCHAR(150),
  status VARCHAR(50) DEFAULT 'preparing',
  shipped_at TIMESTAMPTZ
);

-- ==========================================
-- 6. INVENTORY TRANSACTIONS (Stock Ledger)
-- ==========================================
CREATE TABLE public.inventory_transactions (
  transaction_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  variant_id INT REFERENCES public.product_variants(variant_id) ON DELETE CASCADE,
  quantity_changed INT NOT NULL, -- ค่าบวก (สต็อกเข้า), ค่าลบ (ขายออก/สต็อกลด)
  transaction_type VARCHAR(50) NOT NULL, -- เช่น 'sale', 'restock', 'return', 'adjustment'
  reference_order_id INT REFERENCES public.orders(order_id) ON DELETE SET NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
-- ==========================================
-- 7. VIEWS
-- ==========================================

-- Join categories and subquery variants for summarizing
CREATE OR REPLACE VIEW public.product_list_view AS
SELECT 
    p.product_id,
    p.name AS product_name,
    p.description,
    p.is_active,
    p.created_at,
    c.name AS category_name,
    c.category_id,
    COALESCE(
        (SELECT pv.image_url FROM public.product_variants pv WHERE pv.product_id = p.product_id AND pv.is_main = true LIMIT 1),
        (SELECT pv.image_url FROM public.product_variants pv WHERE pv.product_id = p.product_id ORDER BY pv.variant_id ASC LIMIT 1)
    ) AS image_url,
    (SELECT MIN(pv.price) FROM public.product_variants pv WHERE pv.product_id = p.product_id) AS min_price,
    (SELECT MAX(pv.price) FROM public.product_variants pv WHERE pv.product_id = p.product_id) AS max_price,
    (SELECT SUM(pv.stock_quantity) FROM public.product_variants pv WHERE pv.product_id = p.product_id) AS total_stock,
    (SELECT MIN(pv.low_stock_threshold) FROM public.product_variants pv WHERE pv.product_id = p.product_id) AS low_stock_threshold
FROM public.products p
LEFT JOIN public.categories c ON p.category_id = c.category_id;

-- Join orders with shipments
CREATE OR REPLACE VIEW public.order_list_view AS
SELECT 
    o.order_id,
    o.user_id,
    o.total_amount,
    o.status,
    o.payment_status,
    o.created_at,
    s.status AS shipment_status,
    s.tracking_number,
    u.full_name AS customer_name
FROM public.orders o
LEFT JOIN public.shipments s ON o.order_id = s.order_id
LEFT JOIN public.users u ON o.user_id = u.id;
